/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LabRouteImport } from './routes/lab'
import { Route as ApiDataRouteImport } from './routes/api/data'
import { Route as DemoCoffeeRouteImport } from './routes/demo/coffee'
import { Route as DemoNeonRouteImport } from './routes/demo/neon'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoUsemutationRouteImport } from './routes/demo/usemutation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataRoute = ApiDataRouteImport.update({
  id: '/api/data',
  path: '/api/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCoffeeRoute = DemoCoffeeRouteImport.update({
  id: '/demo/coffee',
  path: '/demo/coffee',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeonRoute = DemoNeonRouteImport.update({
  id: '/demo/neon',
  path: '/demo/neon',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoUsemutationRoute = DemoUsemutationRouteImport.update({
  id: '/demo/usemutation',
  path: '/demo/usemutation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/lab': typeof LabRoute
  '/api/data': typeof ApiDataRoute
  '/demo/coffee': typeof DemoCoffeeRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/usemutation': typeof DemoUsemutationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/lab': typeof LabRoute
  '/api/data': typeof ApiDataRoute
  '/demo/coffee': typeof DemoCoffeeRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/usemutation': typeof DemoUsemutationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/lab': typeof LabRoute
  '/api/data': typeof ApiDataRoute
  '/demo/coffee': typeof DemoCoffeeRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/usemutation': typeof DemoUsemutationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/lab'
    | '/api/data'
    | '/demo/coffee'
    | '/demo/neon'
    | '/demo/table'
    | '/demo/usemutation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/lab'
    | '/api/data'
    | '/demo/coffee'
    | '/demo/neon'
    | '/demo/table'
    | '/demo/usemutation'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/lab'
    | '/api/data'
    | '/demo/coffee'
    | '/demo/neon'
    | '/demo/table'
    | '/demo/usemutation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LabRoute: typeof LabRoute
  ApiDataRoute: typeof ApiDataRoute
  DemoCoffeeRoute: typeof DemoCoffeeRoute
  DemoNeonRoute: typeof DemoNeonRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoUsemutationRoute: typeof DemoUsemutationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data': {
      id: '/api/data'
      path: '/api/data'
      fullPath: '/api/data'
      preLoaderRoute: typeof ApiDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/coffee': {
      id: '/demo/coffee'
      path: '/demo/coffee'
      fullPath: '/demo/coffee'
      preLoaderRoute: typeof DemoCoffeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/neon': {
      id: '/demo/neon'
      path: '/demo/neon'
      fullPath: '/demo/neon'
      preLoaderRoute: typeof DemoNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/usemutation': {
      id: '/demo/usemutation'
      path: '/demo/usemutation'
      fullPath: '/demo/usemutation'
      preLoaderRoute: typeof DemoUsemutationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LabRoute: LabRoute,
  ApiDataRoute: ApiDataRoute,
  DemoCoffeeRoute: DemoCoffeeRoute,
  DemoNeonRoute: DemoNeonRoute,
  DemoTableRoute: DemoTableRoute,
  DemoUsemutationRoute: DemoUsemutationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
